config/routes.rb
Rails.application.routes.draw do
  root 'facts#index'
  
  get '/facts/top10' => 'facts#top_10'
  
  resources :facts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fact.rb
class Fact < ApplicationRecord
    include ImageUploader::Attachment.new(:image)
    
    has_many :vote

    # Fact should not be empty
    validates :fact, presence: true
    
    # Image should not be empty
    validates :image_data, presence: true

    # Fact should not exceed 300 characters
    validates :fact, length: { maximum: 300 }

    # Fact should not allow duplicates
    validates :fact, uniqueness: true

    # Fact should contain Chuck Norris
    validates_format_of :fact, :with => /Chuck Norris/i, :message => 'should contain Chuck Norris'

    scope :random_fact, -> {
        # Set a random offset
        offset = rand(Fact.count)

        # Get the random Fact
        @fact = Fact.offset(offset).first
    }

    scope :top10, ->{
        joins(:vote).
        group("facts.id").
        order("count(votes.id) DESC").
        limit(10)
    }
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :fact
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
  before_action :set_fact, only: [:edit, :update, :destroy]

  # GET /facts
  # GET /facts.json
  def index
    @facts = Fact.all
  end

  # GET /facts/1
  # GET /facts/1.json
  def show
    if params[:id]=="random"
      # # Set a random offset
      # offset = rand(Fact.count)
      
      # # Get the random Fact
      # @fact = Fact.offset(offset).first
      @fact = Fact.random_fact
    else
      redirect_to facts_url
    end
  end

  # Custom Action for Top 10 Facts
  def top_10
    @facts = Fact.top10
  end

  # GET /facts/new
  def new
    @fact = Fact.new
  end

  # GET /facts/1/edit
  def edit
  end

  # POST /facts
  # POST /facts.json
  def create
    @fact = Fact.new(fact_params)

    # Strip fact of white spaces
    @fact.fact.strip!

    respond_to do |format|
      if @fact.save
        format.html { redirect_to @fact, notice: 'Fact was successfully created.' }
        format.json { render :show, status: :created, location: @fact }
      else
        format.html { render :new }
        format.json { render json: @fact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facts/1
  # PATCH/PUT /facts/1.json
  def update
    respond_to do |format|
      if is_voting?

        # Add 1 vote to the fact
        vote = Vote.new
        vote.fact = @fact
        vote.save

        # Redirect to the Facts home page
        format.html { redirect_to facts_url }
        
      elsif @fact.update(fact_params)
        format.html { redirect_to @fact, notice: 'Fact was successfully updated.' }
        format.json { render :show, status: :ok, location: @fact }
      else
        format.html { render :edit }
        format.json { render json: @fact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facts/1
  # DELETE /facts/1.json
  def destroy
    @fact.destroy
    respond_to do |format|
      format.html { redirect_to facts_url, notice: 'Fact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fact
      @fact = Fact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fact_params
      params.require(:fact).permit(:fact, :image)
    end

    def is_voting?
      params.require(:fact)[:vote].present?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/views/facts/_form.html.erb
<%= form_with(model: fact, local: true) do |form| %>
  <% if fact.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(fact.errors.count, "error") %> prohibited this fact from being saved:</h2>

      <ul>
      <% fact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fact %>
    <%= form.text_area :fact, id: :fact_fact %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :fact_image %>
  </div>

  <div class="actions">
    <%= form.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/facts/edit.html.erb
<h1>Editing Fact</h1>

<%= render 'form', fact: @fact %>

app/views/facts/index.html.erb
<p id="notice"><%= notice %></p>

<!-- <h1>Chuck Norris Facts</h1> -->



<div class="row">
  <% @facts.each_with_index do |fact, index| %>
  <div class="col-sm-4">
    <div class="card">
      <div class="photo">
        <%= image_tag fact.image.url,  class:"card-img-top" %>
      </div>
      <div class="card-block">
        <h4 class="card-title">Fact # <%= index+1 %></h4>
        <p class="card-text">
          <%= fact.fact %>
        </p>
        <div class="votes">
          Votes: <%= fact.vote.count %>
        </div>
        <!-- Vote button -->
        <%= form_with model: fact, method: :patch do |f| %>
        <%= f.hidden_field :vote %>
        <div class="card-nav">
          <%= f.submit 'Vote', class: 'btn btn-primary' %>
          <%= link_to button_tag('Edit', class: 'btn btn-info'), edit_fact_path(fact) %>
          <%= link_to button_tag('Delete', class: 'btn btn-info'), fact, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
        <% end %>
      </div>
    </div>
    <br>
  </div>
  <% end %>
</div>

app/views/facts/new.html.erb
<h1>New Fact</h1>

<%= render 'form', fact: @fact %>

app/views/facts/show.html.erb
<h1>Random Chuck Norris Fact</h1><br>
<div class="random-fact">
  <div class="card">
    <div class="photo">
      <%= image_tag @fact.image.url,  class:"card-img-top" %>
    </div>
    <div class="card-block">
      <h4 class="card-title"></h4>
      <p class="card-text">
        <%= @fact.fact %>
      </p>
      <div class="votes">
        Votes: <%= @fact.vote.count %>
      </div>
      <!-- Vote button -->
      <%= form_with model: @fact, method: :patch do |f| %>
      <%= f.hidden_field :vote %>
      <div class="card-nav">
        <%= f.submit 'Vote', class: 'btn btn-primary' %>
        <%= link_to button_tag('Next Random Fact', class: 'btn btn-info'), fact_path('random') %>
      </div>
      <% end %>
    </div>
  </div>
</div>
<%#= link_to 'Edit', edit_fact_path(@fact) %>
<%#= link_to 'Back', facts_path %>

app/views/facts/top_10.html.erb
<h1>Top 10 Chuck Norris Facts</h1><br>
<div class="top-facts">
    <% @facts.each_with_index do |fact, index| %>
    <div class="card">
        <div class="photo">
            <%= image_tag fact.image.url,  class:"card-img-top" %>
            </div>
            <div class="card-block">
            <h4 class="card-title">Rank <%= index + 1 %><br><em>(<%= pluralize(fact.vote.count, 'vote') %>)</em></h4>
            <p class="card-text">
                <%= fact.fact %>
            </p>
            <!-- Vote button -->
            <%= form_with model: fact, method: :patch do |f| %>
            <%= f.hidden_field :vote %>
            <% end %>
        </div>
    </div>
    <br>
    <% end %>

    <div class="back-to-top">
        <a href="#">Back to Top</a>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chuck Norris Facts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light primary-nav">
          <%= link_to 'Chuck Norris Facts', root_path, class:'navbar-brand' %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item <%= 'active' if params[:action] == 'index' %>">
                <%= link_to 'Home', facts_path, class:'nav-link' %>
              </li>
              <li class="nav-item <%= 'active' if params[:action] == 'new' %>">
                <%= link_to 'New Fact', new_fact_path, class:'nav-link' %>
              </li>
              <li class="nav-item <%= 'active' if params[:action] == 'show' %>">
                <%= link_to 'Get a Random Fact', fact_path('random'), class:'nav-link' %>
              </li>
              <li class="nav-item <%= 'active' if params[:action] == 'top_10' %>">
                <%= link_to 'Top 10 Facts', facts_top10_path, class:'nav-link' %>
              </li>
            </ul>
          </div>
        </nav>
      <%= yield %>
    </div>
  </body>
</html>